#!/bin/bash

################################################################################
# Script Name: fingerprint_id.sh
# Description: This script gathers key version information about the Linux
#              system, including the OS, kernel, and critical software versions.
#              It generates a unique identifier based on this information,
#              along with the execution date and time. The output is saved to
#              a timestamped file in /tmp, with a final signature indicating
#              the script's source.
#
# Author: Pedro Anisio Silva
# Version: 1.0
# Date: 01/12/2024
#
# Usage:
# 1. Save this script as `fingerprint_id.sh`.
# 2. Make it executable: `chmod +x fingerprint_id.sh`.
# 3. Run the script: `./fingerprint_id.sh`.
#
# Output:
# - A detailed summary of version information and a unique identifier is
#   displayed on the console.
# - The same details are saved to a file in /tmp named 
#   `system_version_info_<timestamp>.txt`.
################################################################################

# Gather version information
HOSTNAME=$(hostname)
OS_NAME=$(lsb_release -d 2>/dev/null | cut -f2 || cat /etc/os-release | grep 'PRETTY_NAME' | cut -d= -f2 | tr -d '"')
OS_RELEASE=$(lsb_release -c 2>/dev/null | awk '{print $2}' || cat /etc/os-release | grep 'VERSION=' | cut -d= -f2 | tr -d '"')
KERNEL_VERSION=$(uname -r)
GLIBC_VERSION=$(ldd --version | head -n 1 | awk '{print $NF}')
BASH_VERSION=$(bash --version | head -n 1 | awk '{print $4}')
PROXMOX_VERSION=$(pveversion 2>/dev/null || echo "Not a Proxmox Host")
DOCKER_VERSION=$(docker --version 2>/dev/null || echo "Docker not installed")
PYTHON_VERSION=$(python3 --version 2>/dev/null || echo "Python3 not installed")

# Date and time of execution
DATE_TIME=$(date '+%Y-%m-%d %H:%M:%S')

# Combine version information into a unique identifier
UNIQUE_ID=$(echo -n "$HOSTNAME-$OS_NAME-$OS_RELEASE-$KERNEL_VERSION-$GLIBC_VERSION-$BASH_VERSION-$PROXMOX_VERSION-$DOCKER_VERSION-$PYTHON_VERSION-$DATE_TIME" | sha256sum | awk '{print $1}')

# Output version details and unique identifier
OUTPUT_FILE="/tmp/system_version_info_$(date '+%Y%m%d%H%M%S').txt"

echo "System Version Details:" | tee "$OUTPUT_FILE"
echo "Date and Time: $DATE_TIME" | tee -a "$OUTPUT_FILE"
echo "Hostname: $HOSTNAME" | tee -a "$OUTPUT_FILE"
echo "OS Name: $OS_NAME" | tee -a "$OUTPUT_FILE"
echo "OS Release: $OS_RELEASE" | tee -a "$OUTPUT_FILE"
echo "Kernel Version: $KERNEL_VERSION" | tee -a "$OUTPUT_FILE"
echo "glibc Version: $GLIBC_VERSION" | tee -a "$OUTPUT_FILE"
echo "Bash Version: $BASH_VERSION" | tee -a "$OUTPUT_FILE"
echo "Proxmox Version: $PROXMOX_VERSION" | tee -a "$OUTPUT_FILE"
echo "Docker Version: $DOCKER_VERSION" | tee -a "$OUTPUT_FILE"
echo "Python3 Version: $PYTHON_VERSION" | tee -a "$OUTPUT_FILE"
echo | tee -a "$OUTPUT_FILE"
echo "Unique Identifier: $UNIQUE_ID" | tee -a "$OUTPUT_FILE"
echo | tee -a "$OUTPUT_FILE"
echo "Generated by debian/scripts/fingerprint_id.sh" | tee -a "$OUTPUT_FILE"

echo "Version
