#!/bin/bash

# Gather version information
HOSTNAME=$(hostname)
OS_NAME=$(lsb_release -d 2>/dev/null | cut -f2 || cat /etc/os-release | grep 'PRETTY_NAME' | cut -d= -f2 | tr -d '"')
OS_RELEASE=$(lsb_release -c 2>/dev/null | awk '{print $2}' || cat /etc/os-release | grep 'VERSION=' | cut -d= -f2 | tr -d '"')
KERNEL_VERSION=$(uname -r)
GLIBC_VERSION=$(ldd --version | head -n 1 | awk '{print $NF}')
BASH_VERSION=$(bash --version | head -n 1 | awk '{print $4}')
PROXMOX_VERSION=$(pveversion 2>/dev/null || echo "Not a Proxmox Host")
DOCKER_VERSION=$(docker --version 2>/dev/null || echo "Docker not installed")
PYTHON_VERSION=$(python3 --version 2>/dev/null || echo "Python3 not installed")

# Date and time of execution
DATE_TIME=$(date '+%Y-%m-%d %H:%M:%S')

# Combine version information into a unique identifier
UNIQUE_ID=$(echo -n "$HOSTNAME-$OS_NAME-$OS_RELEASE-$KERNEL_VERSION-$GLIBC_VERSION-$BASH_VERSION-$PROXMOX_VERSION-$DOCKER_VERSION-$PYTHON_VERSION-$DATE_TIME" | sha256sum | awk '{print $1}')

# Output version details and unique identifier
OUTPUT_FILE="/tmp/system_version_info_$(date '+%Y%m%d%H%M%S').txt"

echo "System Version Details:" | tee "$OUTPUT_FILE"
echo "Date and Time: $DATE_TIME" | tee -a "$OUTPUT_FILE"
echo "Hostname: $HOSTNAME" | tee -a "$OUTPUT_FILE"
echo "OS Name: $OS_NAME" | tee -a "$OUTPUT_FILE"
echo "OS Release: $OS_RELEASE" | tee -a "$OUTPUT_FILE"
echo "Kernel Version: $KERNEL_VERSION" | tee -a "$OUTPUT_FILE"
echo "glibc Version: $GLIBC_VERSION" | tee -a "$OUTPUT_FILE"
echo "Bash Version: $BASH_VERSION" | tee -a "$OUTPUT_FILE"
echo "Proxmox Version: $PROXMOX_VERSION" | tee -a "$OUTPUT_FILE"
echo "Docker Version: $DOCKER_VERSION" | tee -a "$OUTPUT_FILE"
echo "Python3 Version: $PYTHON_VERSION" | tee -a "$OUTPUT_FILE"
echo | tee -a "$OUTPUT_FILE"
echo "Unique Identifier: $UNIQUE_ID" | tee -a "$OUTPUT_FILE"
echo "Version information saved to '$OUTPUT_FILE'."
echo "Generated by debian/scripts/fingerprint_id.sh" | tee -a "$OUTPUT_FILE"

